// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/llm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMEmpty) Reset() {
	*x = LLMEmpty{}
	mi := &file_proto_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMEmpty) ProtoMessage() {}

func (x *LLMEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMEmpty.ProtoReflect.Descriptor instead.
func (*LLMEmpty) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{0}
}

type LLMName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMName) Reset() {
	*x = LLMName{}
	mi := &file_proto_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMName) ProtoMessage() {}

func (x *LLMName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMName.ProtoReflect.Descriptor instead.
func (*LLMName) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{1}
}

func (x *LLMName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LLMMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMMessage) Reset() {
	*x = LLMMessage{}
	mi := &file_proto_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMMessage) ProtoMessage() {}

func (x *LLMMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMMessage.ProtoReflect.Descriptor instead.
func (*LLMMessage) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{2}
}

func (x *LLMMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LLMMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Messages      []*LLMMessage          `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_proto_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompleteRequest) GetMessages() []*LLMMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_llm_proto protoreflect.FileDescriptor

const file_proto_llm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/llm.proto\x12\x11console.plugin.v1\"\n" +
	"\n" +
	"\bLLMEmpty\"\x1d\n" +
	"\aLLMName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\n" +
	"LLMMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x99\x01\n" +
	"\x0fCompleteRequest\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x129\n" +
	"\bmessages\x18\x02 \x03(\v2\x1d.console.plugin.v1.LLMMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"&\n" +
	"\x10CompleteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\xa2\x01\n" +
	"\n" +
	"LLMService\x12?\n" +
	"\x04Name\x12\x1b.console.plugin.v1.LLMEmpty\x1a\x1a.console.plugin.v1.LLMName\x12S\n" +
	"\bComplete\x12\".console.plugin.v1.CompleteRequest\x1a#.console.plugin.v1.CompleteResponseB;Z9github.com/moosequest/console/internal/plugin/proto;protob\x06proto3"

var (
	file_proto_llm_proto_rawDescOnce sync.Once
	file_proto_llm_proto_rawDescData []byte
)

func file_proto_llm_proto_rawDescGZIP() []byte {
	file_proto_llm_proto_rawDescOnce.Do(func() {
		file_proto_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)))
	})
	return file_proto_llm_proto_rawDescData
}

var file_proto_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_llm_proto_goTypes = []any{
	(*LLMEmpty)(nil),         // 0: console.plugin.v1.LLMEmpty
	(*LLMName)(nil),          // 1: console.plugin.v1.LLMName
	(*LLMMessage)(nil),       // 2: console.plugin.v1.LLMMessage
	(*CompleteRequest)(nil),  // 3: console.plugin.v1.CompleteRequest
	(*CompleteResponse)(nil), // 4: console.plugin.v1.CompleteResponse
}
var file_proto_llm_proto_depIdxs = []int32{
	2, // 0: console.plugin.v1.CompleteRequest.messages:type_name -> console.plugin.v1.LLMMessage
	0, // 1: console.plugin.v1.LLMService.Name:input_type -> console.plugin.v1.LLMEmpty
	3, // 2: console.plugin.v1.LLMService.Complete:input_type -> console.plugin.v1.CompleteRequest
	1, // 3: console.plugin.v1.LLMService.Name:output_type -> console.plugin.v1.LLMName
	4, // 4: console.plugin.v1.LLMService.Complete:output_type -> console.plugin.v1.CompleteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_llm_proto_init() }
func file_proto_llm_proto_init() {
	if File_proto_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_proto_goTypes,
		DependencyIndexes: file_proto_llm_proto_depIdxs,
		MessageInfos:      file_proto_llm_proto_msgTypes,
	}.Build()
	File_proto_llm_proto = out.File
	file_proto_llm_proto_goTypes = nil
	file_proto_llm_proto_depIdxs = nil
}
