// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/notify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyEmpty) Reset() {
	*x = NotifyEmpty{}
	mi := &file_proto_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyEmpty) ProtoMessage() {}

func (x *NotifyEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyEmpty.ProtoReflect.Descriptor instead.
func (*NotifyEmpty) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{0}
}

type NotifierName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifierName) Reset() {
	*x = NotifierName{}
	mi := &file_proto_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifierName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierName) ProtoMessage() {}

func (x *NotifierName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifierName.ProtoReflect.Descriptor instead.
func (*NotifierName) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotifierName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Event mirrors core.Event.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	Flag          string                 `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	From          int32                  `protobuf:"varint,6,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,7,opt,name=to,proto3" json:"to,omitempty"`
	AtUnixNano    int64                  `protobuf:"varint,8,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Event) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Event) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Event) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Event) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

var File_proto_notify_proto protoreflect.FileDescriptor

const file_proto_notify_proto_rawDesc = "" +
	"\n" +
	"\x12proto/notify.proto\x12\x11console.plugin.v1\"\r\n" +
	"\vNotifyEmpty\"\"\n" +
	"\fNotifierName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc3\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04flag\x18\x05 \x01(\tR\x04flag\x12\x12\n" +
	"\x04from\x18\x06 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\a \x01(\x05R\x02to\x12 \n" +
	"\fat_unix_nano\x18\b \x01(\x03R\n" +
	"atUnixNano2\x9e\x01\n" +
	"\x0fNotifierService\x12G\n" +
	"\x04Name\x12\x1e.console.plugin.v1.NotifyEmpty\x1a\x1f.console.plugin.v1.NotifierName\x12B\n" +
	"\x06Notify\x12\x18.console.plugin.v1.Event\x1a\x1e.console.plugin.v1.NotifyEmptyB;Z9github.com/moosequest/console/internal/plugin/proto;protob\x06proto3"

var (
	file_proto_notify_proto_rawDescOnce sync.Once
	file_proto_notify_proto_rawDescData []byte
)

func file_proto_notify_proto_rawDescGZIP() []byte {
	file_proto_notify_proto_rawDescOnce.Do(func() {
		file_proto_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)))
	})
	return file_proto_notify_proto_rawDescData
}

var file_proto_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_notify_proto_goTypes = []any{
	(*NotifyEmpty)(nil),  // 0: console.plugin.v1.NotifyEmpty
	(*NotifierName)(nil), // 1: console.plugin.v1.NotifierName
	(*Event)(nil),        // 2: console.plugin.v1.Event
}
var file_proto_notify_proto_depIdxs = []int32{
	0, // 0: console.plugin.v1.NotifierService.Name:input_type -> console.plugin.v1.NotifyEmpty
	2, // 1: console.plugin.v1.NotifierService.Notify:input_type -> console.plugin.v1.Event
	1, // 2: console.plugin.v1.NotifierService.Name:output_type -> console.plugin.v1.NotifierName
	0, // 3: console.plugin.v1.NotifierService.Notify:output_type -> console.plugin.v1.NotifyEmpty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_notify_proto_init() }
func file_proto_notify_proto_init() {
	if File_proto_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notify_proto_goTypes,
		DependencyIndexes: file_proto_notify_proto_depIdxs,
		MessageInfos:      file_proto_notify_proto_msgTypes,
	}.Build()
	File_proto_notify_proto = out.File
	file_proto_notify_proto_goTypes = nil
	file_proto_notify_proto_depIdxs = nil
}
