// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEmpty) Reset() {
	*x = StatusEmpty{}
	mi := &file_proto_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEmpty) ProtoMessage() {}

func (x *StatusEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEmpty.ProtoReflect.Descriptor instead.
func (*StatusEmpty) Descriptor() ([]byte, []int) {
	return file_proto_status_proto_rawDescGZIP(), []int{0}
}

type StatusName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusName) Reset() {
	*x = StatusName{}
	mi := &file_proto_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusName) ProtoMessage() {}

func (x *StatusName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusName.ProtoReflect.Descriptor instead.
func (*StatusName) Descriptor() ([]byte, []int) {
	return file_proto_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// StatusComponent mirrors the fields of core.Component a provider reads.
type StatusComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusComponent) Reset() {
	*x = StatusComponent{}
	mi := &file_proto_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusComponent) ProtoMessage() {}

func (x *StatusComponent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusComponent.ProtoReflect.Descriptor instead.
func (*StatusComponent) Descriptor() ([]byte, []int) {
	return file_proto_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusComponent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatusComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusComponent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StatusComponent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StatusComponent) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// StatusCheck mirrors core.Check. Provider errors are carried in state/message,
// not as a gRPC error, matching the in-process contract.
type StatusCheck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Component         string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	State             int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LatencyNanos      int64                  `protobuf:"varint,4,opt,name=latency_nanos,json=latencyNanos,proto3" json:"latency_nanos,omitempty"`
	CheckedAtUnixNano int64                  `protobuf:"varint,5,opt,name=checked_at_unix_nano,json=checkedAtUnixNano,proto3" json:"checked_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusCheck) Reset() {
	*x = StatusCheck{}
	mi := &file_proto_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCheck) ProtoMessage() {}

func (x *StatusCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCheck.ProtoReflect.Descriptor instead.
func (*StatusCheck) Descriptor() ([]byte, []int) {
	return file_proto_status_proto_rawDescGZIP(), []int{3}
}

func (x *StatusCheck) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *StatusCheck) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StatusCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusCheck) GetLatencyNanos() int64 {
	if x != nil {
		return x.LatencyNanos
	}
	return 0
}

func (x *StatusCheck) GetCheckedAtUnixNano() int64 {
	if x != nil {
		return x.CheckedAtUnixNano
	}
	return 0
}

var File_proto_status_proto protoreflect.FileDescriptor

const file_proto_status_proto_rawDesc = "" +
	"\n" +
	"\x12proto/status.proto\x12\x11console.plugin.v1\"\r\n" +
	"\vStatusEmpty\" \n" +
	"\n" +
	"StatusName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf8\x01\n" +
	"\x0fStatusComponent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12F\n" +
	"\x06config\x18\x05 \x03(\v2..console.plugin.v1.StatusComponent.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\vStatusCheck\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rlatency_nanos\x18\x04 \x01(\x03R\flatencyNanos\x12/\n" +
	"\x14checked_at_unix_nano\x18\x05 \x01(\x03R\x11checkedAtUnixNano2\xab\x01\n" +
	"\x15StatusProviderService\x12E\n" +
	"\x04Name\x12\x1e.console.plugin.v1.StatusEmpty\x1a\x1d.console.plugin.v1.StatusName\x12K\n" +
	"\x05Check\x12\".console.plugin.v1.StatusComponent\x1a\x1e.console.plugin.v1.StatusCheckB;Z9github.com/moosequest/console/internal/plugin/proto;protob\x06proto3"

var (
	file_proto_status_proto_rawDescOnce sync.Once
	file_proto_status_proto_rawDescData []byte
)

func file_proto_status_proto_rawDescGZIP() []byte {
	file_proto_status_proto_rawDescOnce.Do(func() {
		file_proto_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_status_proto_rawDesc), len(file_proto_status_proto_rawDesc)))
	})
	return file_proto_status_proto_rawDescData
}

var file_proto_status_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_status_proto_goTypes = []any{
	(*StatusEmpty)(nil),     // 0: console.plugin.v1.StatusEmpty
	(*StatusName)(nil),      // 1: console.plugin.v1.StatusName
	(*StatusComponent)(nil), // 2: console.plugin.v1.StatusComponent
	(*StatusCheck)(nil),     // 3: console.plugin.v1.StatusCheck
	nil,                     // 4: console.plugin.v1.StatusComponent.ConfigEntry
}
var file_proto_status_proto_depIdxs = []int32{
	4, // 0: console.plugin.v1.StatusComponent.config:type_name -> console.plugin.v1.StatusComponent.ConfigEntry
	0, // 1: console.plugin.v1.StatusProviderService.Name:input_type -> console.plugin.v1.StatusEmpty
	2, // 2: console.plugin.v1.StatusProviderService.Check:input_type -> console.plugin.v1.StatusComponent
	1, // 3: console.plugin.v1.StatusProviderService.Name:output_type -> console.plugin.v1.StatusName
	3, // 4: console.plugin.v1.StatusProviderService.Check:output_type -> console.plugin.v1.StatusCheck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_status_proto_init() }
func file_proto_status_proto_init() {
	if File_proto_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_status_proto_rawDesc), len(file_proto_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_status_proto_goTypes,
		DependencyIndexes: file_proto_status_proto_depIdxs,
		MessageInfos:      file_proto_status_proto_msgTypes,
	}.Build()
	File_proto_status_proto = out.File
	file_proto_status_proto_goTypes = nil
	file_proto_status_proto_depIdxs = nil
}
