// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/status.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatusProviderService_Name_FullMethodName  = "/console.plugin.v1.StatusProviderService/Name"
	StatusProviderService_Check_FullMethodName = "/console.plugin.v1.StatusProviderService/Check"
)

// StatusProviderServiceClient is the client API for StatusProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StatusProviderService is the gRPC contract for a Console status-provider
// plugin. It mirrors the Go status.Provider interface: a named health check.
type StatusProviderServiceClient interface {
	Name(ctx context.Context, in *StatusEmpty, opts ...grpc.CallOption) (*StatusName, error)
	Check(ctx context.Context, in *StatusComponent, opts ...grpc.CallOption) (*StatusCheck, error)
}

type statusProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusProviderServiceClient(cc grpc.ClientConnInterface) StatusProviderServiceClient {
	return &statusProviderServiceClient{cc}
}

func (c *statusProviderServiceClient) Name(ctx context.Context, in *StatusEmpty, opts ...grpc.CallOption) (*StatusName, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusName)
	err := c.cc.Invoke(ctx, StatusProviderService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusProviderServiceClient) Check(ctx context.Context, in *StatusComponent, opts ...grpc.CallOption) (*StatusCheck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusCheck)
	err := c.cc.Invoke(ctx, StatusProviderService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusProviderServiceServer is the server API for StatusProviderService service.
// All implementations must embed UnimplementedStatusProviderServiceServer
// for forward compatibility.
//
// StatusProviderService is the gRPC contract for a Console status-provider
// plugin. It mirrors the Go status.Provider interface: a named health check.
type StatusProviderServiceServer interface {
	Name(context.Context, *StatusEmpty) (*StatusName, error)
	Check(context.Context, *StatusComponent) (*StatusCheck, error)
	mustEmbedUnimplementedStatusProviderServiceServer()
}

// UnimplementedStatusProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusProviderServiceServer struct{}

func (UnimplementedStatusProviderServiceServer) Name(context.Context, *StatusEmpty) (*StatusName, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedStatusProviderServiceServer) Check(context.Context, *StatusComponent) (*StatusCheck, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedStatusProviderServiceServer) mustEmbedUnimplementedStatusProviderServiceServer() {}
func (UnimplementedStatusProviderServiceServer) testEmbeddedByValue()                               {}

// UnsafeStatusProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusProviderServiceServer will
// result in compilation errors.
type UnsafeStatusProviderServiceServer interface {
	mustEmbedUnimplementedStatusProviderServiceServer()
}

func RegisterStatusProviderServiceServer(s grpc.ServiceRegistrar, srv StatusProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedStatusProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatusProviderService_ServiceDesc, srv)
}

func _StatusProviderService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusProviderServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusProviderService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusProviderServiceServer).Name(ctx, req.(*StatusEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatusProviderService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusComponent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusProviderServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusProviderService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusProviderServiceServer).Check(ctx, req.(*StatusComponent))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusProviderService_ServiceDesc is the grpc.ServiceDesc for StatusProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.plugin.v1.StatusProviderService",
	HandlerType: (*StatusProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _StatusProviderService_Name_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _StatusProviderService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/status.proto",
}
