// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_CreateFlag_FullMethodName      = "/console.plugin.v1.StoreService/CreateFlag"
	StoreService_GetFlag_FullMethodName         = "/console.plugin.v1.StoreService/GetFlag"
	StoreService_ListFlags_FullMethodName       = "/console.plugin.v1.StoreService/ListFlags"
	StoreService_UpdateFlag_FullMethodName      = "/console.plugin.v1.StoreService/UpdateFlag"
	StoreService_DeleteFlag_FullMethodName      = "/console.plugin.v1.StoreService/DeleteFlag"
	StoreService_CreateComponent_FullMethodName = "/console.plugin.v1.StoreService/CreateComponent"
	StoreService_GetComponent_FullMethodName    = "/console.plugin.v1.StoreService/GetComponent"
	StoreService_ListComponents_FullMethodName  = "/console.plugin.v1.StoreService/ListComponents"
	StoreService_UpdateComponent_FullMethodName = "/console.plugin.v1.StoreService/UpdateComponent"
	StoreService_DeleteComponent_FullMethodName = "/console.plugin.v1.StoreService/DeleteComponent"
	StoreService_RecordCheck_FullMethodName     = "/console.plugin.v1.StoreService/RecordCheck"
	StoreService_LatestCheck_FullMethodName     = "/console.plugin.v1.StoreService/LatestCheck"
	StoreService_LatestChecks_FullMethodName    = "/console.plugin.v1.StoreService/LatestChecks"
	StoreService_Ping_FullMethodName            = "/console.plugin.v1.StoreService/Ping"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoreService is the gRPC contract for a Console storage-backend plugin. It
// mirrors the Go store.Store interface. Not-found and conflict conditions are
// conveyed via gRPC status codes (NotFound, AlreadyExists) and mapped back to
// core.ErrNotFound / core.ErrConflict on the host side.
type StoreServiceClient interface {
	CreateFlag(ctx context.Context, in *Flag, opts ...grpc.CallOption) (*Empty, error)
	GetFlag(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Flag, error)
	ListFlags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlagList, error)
	UpdateFlag(ctx context.Context, in *Flag, opts ...grpc.CallOption) (*Empty, error)
	DeleteFlag(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
	CreateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Empty, error)
	GetComponent(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Component, error)
	ListComponents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentList, error)
	UpdateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Empty, error)
	DeleteComponent(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
	RecordCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*Empty, error)
	LatestCheck(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Check, error)
	LatestChecks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckList, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) CreateFlag(ctx context.Context, in *Flag, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_CreateFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetFlag(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Flag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flag)
	err := c.cc.Invoke(ctx, StoreService_GetFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListFlags(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlagList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlagList)
	err := c.cc.Invoke(ctx, StoreService_ListFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateFlag(ctx context.Context, in *Flag, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_UpdateFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteFlag(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) CreateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_CreateComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetComponent(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Component, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Component)
	err := c.cc.Invoke(ctx, StoreService_GetComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListComponents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentList)
	err := c.cc.Invoke(ctx, StoreService_ListComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_UpdateComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DeleteComponent(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_DeleteComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) RecordCheck(ctx context.Context, in *Check, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_RecordCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) LatestCheck(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Check, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Check)
	err := c.cc.Invoke(ctx, StoreService_LatestCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) LatestChecks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckList)
	err := c.cc.Invoke(ctx, StoreService_LatestChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StoreService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
//
// StoreService is the gRPC contract for a Console storage-backend plugin. It
// mirrors the Go store.Store interface. Not-found and conflict conditions are
// conveyed via gRPC status codes (NotFound, AlreadyExists) and mapped back to
// core.ErrNotFound / core.ErrConflict on the host side.
type StoreServiceServer interface {
	CreateFlag(context.Context, *Flag) (*Empty, error)
	GetFlag(context.Context, *Key) (*Flag, error)
	ListFlags(context.Context, *Empty) (*FlagList, error)
	UpdateFlag(context.Context, *Flag) (*Empty, error)
	DeleteFlag(context.Context, *Key) (*Empty, error)
	CreateComponent(context.Context, *Component) (*Empty, error)
	GetComponent(context.Context, *Key) (*Component, error)
	ListComponents(context.Context, *Empty) (*ComponentList, error)
	UpdateComponent(context.Context, *Component) (*Empty, error)
	DeleteComponent(context.Context, *Key) (*Empty, error)
	RecordCheck(context.Context, *Check) (*Empty, error)
	LatestCheck(context.Context, *Key) (*Check, error)
	LatestChecks(context.Context, *Empty) (*CheckList, error)
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) CreateFlag(context.Context, *Flag) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFlag not implemented")
}
func (UnimplementedStoreServiceServer) GetFlag(context.Context, *Key) (*Flag, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlag not implemented")
}
func (UnimplementedStoreServiceServer) ListFlags(context.Context, *Empty) (*FlagList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFlags not implemented")
}
func (UnimplementedStoreServiceServer) UpdateFlag(context.Context, *Flag) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFlag not implemented")
}
func (UnimplementedStoreServiceServer) DeleteFlag(context.Context, *Key) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFlag not implemented")
}
func (UnimplementedStoreServiceServer) CreateComponent(context.Context, *Component) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComponent not implemented")
}
func (UnimplementedStoreServiceServer) GetComponent(context.Context, *Key) (*Component, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComponent not implemented")
}
func (UnimplementedStoreServiceServer) ListComponents(context.Context, *Empty) (*ComponentList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComponents not implemented")
}
func (UnimplementedStoreServiceServer) UpdateComponent(context.Context, *Component) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComponent not implemented")
}
func (UnimplementedStoreServiceServer) DeleteComponent(context.Context, *Key) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComponent not implemented")
}
func (UnimplementedStoreServiceServer) RecordCheck(context.Context, *Check) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordCheck not implemented")
}
func (UnimplementedStoreServiceServer) LatestCheck(context.Context, *Key) (*Check, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestCheck not implemented")
}
func (UnimplementedStoreServiceServer) LatestChecks(context.Context, *Empty) (*CheckList, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestChecks not implemented")
}
func (UnimplementedStoreServiceServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_CreateFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CreateFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_CreateFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CreateFlag(ctx, req.(*Flag))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetFlag(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListFlags(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpdateFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateFlag(ctx, req.(*Flag))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteFlag(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_CreateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Component)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CreateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_CreateComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CreateComponent(ctx, req.(*Component))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetComponent(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListComponents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Component)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpdateComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateComponent(ctx, req.(*Component))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DeleteComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DeleteComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DeleteComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DeleteComponent(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_RecordCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RecordCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RecordCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RecordCheck(ctx, req.(*Check))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_LatestCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).LatestCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_LatestCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).LatestCheck(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_LatestChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).LatestChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_LatestChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).LatestChecks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.plugin.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFlag",
			Handler:    _StoreService_CreateFlag_Handler,
		},
		{
			MethodName: "GetFlag",
			Handler:    _StoreService_GetFlag_Handler,
		},
		{
			MethodName: "ListFlags",
			Handler:    _StoreService_ListFlags_Handler,
		},
		{
			MethodName: "UpdateFlag",
			Handler:    _StoreService_UpdateFlag_Handler,
		},
		{
			MethodName: "DeleteFlag",
			Handler:    _StoreService_DeleteFlag_Handler,
		},
		{
			MethodName: "CreateComponent",
			Handler:    _StoreService_CreateComponent_Handler,
		},
		{
			MethodName: "GetComponent",
			Handler:    _StoreService_GetComponent_Handler,
		},
		{
			MethodName: "ListComponents",
			Handler:    _StoreService_ListComponents_Handler,
		},
		{
			MethodName: "UpdateComponent",
			Handler:    _StoreService_UpdateComponent_Handler,
		},
		{
			MethodName: "DeleteComponent",
			Handler:    _StoreService_DeleteComponent_Handler,
		},
		{
			MethodName: "RecordCheck",
			Handler:    _StoreService_RecordCheck_Handler,
		},
		{
			MethodName: "LatestCheck",
			Handler:    _StoreService_LatestCheck_Handler,
		},
		{
			MethodName: "LatestChecks",
			Handler:    _StoreService_LatestChecks_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StoreService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/store.proto",
}
