// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/store.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{0}
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_proto_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_proto_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{2}
}

func (x *Variant) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Variant) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Variant) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Flag struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled           bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Scope             string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Rollout           int32                  `protobuf:"varint,5,opt,name=rollout,proto3" json:"rollout,omitempty"`
	Variants          []*Variant             `protobuf:"bytes,6,rep,name=variants,proto3" json:"variants,omitempty"`
	Cohort            string                 `protobuf:"bytes,7,opt,name=cohort,proto3" json:"cohort,omitempty"`
	Experiment        string                 `protobuf:"bytes,8,opt,name=experiment,proto3" json:"experiment,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,9,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	UpdatedAtUnixNano int64                  `protobuf:"varint,10,opt,name=updated_at_unix_nano,json=updatedAtUnixNano,proto3" json:"updated_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_proto_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{3}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flag) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Flag) GetRollout() int32 {
	if x != nil {
		return x.Rollout
	}
	return 0
}

func (x *Flag) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Flag) GetCohort() string {
	if x != nil {
		return x.Cohort
	}
	return ""
}

func (x *Flag) GetExperiment() string {
	if x != nil {
		return x.Experiment
	}
	return ""
}

func (x *Flag) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *Flag) GetUpdatedAtUnixNano() int64 {
	if x != nil {
		return x.UpdatedAtUnixNano
	}
	return 0
}

type FlagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*Flag                `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagList) Reset() {
	*x = FlagList{}
	mi := &file_proto_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagList) ProtoMessage() {}

func (x *FlagList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagList.ProtoReflect.Descriptor instead.
func (*FlagList) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{4}
}

func (x *FlagList) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type Component struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Provider          string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Config            map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAtUnixNano int64                  `protobuf:"varint,6,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	UpdatedAtUnixNano int64                  `protobuf:"varint,7,opt,name=updated_at_unix_nano,json=updatedAtUnixNano,proto3" json:"updated_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_proto_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{5}
}

func (x *Component) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Component) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Component) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Component) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *Component) GetUpdatedAtUnixNano() int64 {
	if x != nil {
		return x.UpdatedAtUnixNano
	}
	return 0
}

type ComponentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Components    []*Component           `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentList) Reset() {
	*x = ComponentList{}
	mi := &file_proto_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentList) ProtoMessage() {}

func (x *ComponentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentList.ProtoReflect.Descriptor instead.
func (*ComponentList) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentList) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

type Check struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Component         string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	State             int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LatencyNanos      int64                  `protobuf:"varint,4,opt,name=latency_nanos,json=latencyNanos,proto3" json:"latency_nanos,omitempty"`
	CheckedAtUnixNano int64                  `protobuf:"varint,5,opt,name=checked_at_unix_nano,json=checkedAtUnixNano,proto3" json:"checked_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_proto_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{7}
}

func (x *Check) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Check) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Check) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Check) GetLatencyNanos() int64 {
	if x != nil {
		return x.LatencyNanos
	}
	return 0
}

func (x *Check) GetCheckedAtUnixNano() int64 {
	if x != nil {
		return x.CheckedAtUnixNano
	}
	return 0
}

type CheckList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*Check               `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckList) Reset() {
	*x = CheckList{}
	mi := &file_proto_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckList) ProtoMessage() {}

func (x *CheckList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckList.ProtoReflect.Descriptor instead.
func (*CheckList) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{8}
}

func (x *CheckList) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_proto_store_proto protoreflect.FileDescriptor

const file_proto_store_proto_rawDesc = "" +
	"\n" +
	"\x11proto/store.proto\x12\x11console.plugin.v1\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\aVariant\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"\xd6\x02\n" +
	"\x04Flag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x18\n" +
	"\arollout\x18\x05 \x01(\x05R\arollout\x126\n" +
	"\bvariants\x18\x06 \x03(\v2\x1a.console.plugin.v1.VariantR\bvariants\x12\x16\n" +
	"\x06cohort\x18\a \x01(\tR\x06cohort\x12\x1e\n" +
	"\n" +
	"experiment\x18\b \x01(\tR\n" +
	"experiment\x12/\n" +
	"\x14created_at_unix_nano\x18\t \x01(\x03R\x11createdAtUnixNano\x12/\n" +
	"\x14updated_at_unix_nano\x18\n" +
	" \x01(\x03R\x11updatedAtUnixNano\"9\n" +
	"\bFlagList\x12-\n" +
	"\x05flags\x18\x01 \x03(\v2\x17.console.plugin.v1.FlagR\x05flags\"\xce\x02\n" +
	"\tComponent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12@\n" +
	"\x06config\x18\x05 \x03(\v2(.console.plugin.v1.Component.ConfigEntryR\x06config\x12/\n" +
	"\x14created_at_unix_nano\x18\x06 \x01(\x03R\x11createdAtUnixNano\x12/\n" +
	"\x14updated_at_unix_nano\x18\a \x01(\x03R\x11updatedAtUnixNano\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\rComponentList\x12<\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\x1c.console.plugin.v1.ComponentR\n" +
	"components\"\xab\x01\n" +
	"\x05Check\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rlatency_nanos\x18\x04 \x01(\x03R\flatencyNanos\x12/\n" +
	"\x14checked_at_unix_nano\x18\x05 \x01(\x03R\x11checkedAtUnixNano\"=\n" +
	"\tCheckList\x120\n" +
	"\x06checks\x18\x01 \x03(\v2\x18.console.plugin.v1.CheckR\x06checks2\xc7\a\n" +
	"\fStoreService\x12?\n" +
	"\n" +
	"CreateFlag\x12\x17.console.plugin.v1.Flag\x1a\x18.console.plugin.v1.Empty\x12:\n" +
	"\aGetFlag\x12\x16.console.plugin.v1.Key\x1a\x17.console.plugin.v1.Flag\x12B\n" +
	"\tListFlags\x12\x18.console.plugin.v1.Empty\x1a\x1b.console.plugin.v1.FlagList\x12?\n" +
	"\n" +
	"UpdateFlag\x12\x17.console.plugin.v1.Flag\x1a\x18.console.plugin.v1.Empty\x12>\n" +
	"\n" +
	"DeleteFlag\x12\x16.console.plugin.v1.Key\x1a\x18.console.plugin.v1.Empty\x12I\n" +
	"\x0fCreateComponent\x12\x1c.console.plugin.v1.Component\x1a\x18.console.plugin.v1.Empty\x12D\n" +
	"\fGetComponent\x12\x16.console.plugin.v1.Key\x1a\x1c.console.plugin.v1.Component\x12L\n" +
	"\x0eListComponents\x12\x18.console.plugin.v1.Empty\x1a .console.plugin.v1.ComponentList\x12I\n" +
	"\x0fUpdateComponent\x12\x1c.console.plugin.v1.Component\x1a\x18.console.plugin.v1.Empty\x12C\n" +
	"\x0fDeleteComponent\x12\x16.console.plugin.v1.Key\x1a\x18.console.plugin.v1.Empty\x12A\n" +
	"\vRecordCheck\x12\x18.console.plugin.v1.Check\x1a\x18.console.plugin.v1.Empty\x12?\n" +
	"\vLatestCheck\x12\x16.console.plugin.v1.Key\x1a\x18.console.plugin.v1.Check\x12F\n" +
	"\fLatestChecks\x12\x18.console.plugin.v1.Empty\x1a\x1c.console.plugin.v1.CheckList\x12:\n" +
	"\x04Ping\x12\x18.console.plugin.v1.Empty\x1a\x18.console.plugin.v1.EmptyB;Z9github.com/moosequest/console/internal/plugin/proto;protob\x06proto3"

var (
	file_proto_store_proto_rawDescOnce sync.Once
	file_proto_store_proto_rawDescData []byte
)

func file_proto_store_proto_rawDescGZIP() []byte {
	file_proto_store_proto_rawDescOnce.Do(func() {
		file_proto_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_store_proto_rawDesc), len(file_proto_store_proto_rawDesc)))
	})
	return file_proto_store_proto_rawDescData
}

var file_proto_store_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_store_proto_goTypes = []any{
	(*Empty)(nil),         // 0: console.plugin.v1.Empty
	(*Key)(nil),           // 1: console.plugin.v1.Key
	(*Variant)(nil),       // 2: console.plugin.v1.Variant
	(*Flag)(nil),          // 3: console.plugin.v1.Flag
	(*FlagList)(nil),      // 4: console.plugin.v1.FlagList
	(*Component)(nil),     // 5: console.plugin.v1.Component
	(*ComponentList)(nil), // 6: console.plugin.v1.ComponentList
	(*Check)(nil),         // 7: console.plugin.v1.Check
	(*CheckList)(nil),     // 8: console.plugin.v1.CheckList
	nil,                   // 9: console.plugin.v1.Component.ConfigEntry
}
var file_proto_store_proto_depIdxs = []int32{
	2,  // 0: console.plugin.v1.Flag.variants:type_name -> console.plugin.v1.Variant
	3,  // 1: console.plugin.v1.FlagList.flags:type_name -> console.plugin.v1.Flag
	9,  // 2: console.plugin.v1.Component.config:type_name -> console.plugin.v1.Component.ConfigEntry
	5,  // 3: console.plugin.v1.ComponentList.components:type_name -> console.plugin.v1.Component
	7,  // 4: console.plugin.v1.CheckList.checks:type_name -> console.plugin.v1.Check
	3,  // 5: console.plugin.v1.StoreService.CreateFlag:input_type -> console.plugin.v1.Flag
	1,  // 6: console.plugin.v1.StoreService.GetFlag:input_type -> console.plugin.v1.Key
	0,  // 7: console.plugin.v1.StoreService.ListFlags:input_type -> console.plugin.v1.Empty
	3,  // 8: console.plugin.v1.StoreService.UpdateFlag:input_type -> console.plugin.v1.Flag
	1,  // 9: console.plugin.v1.StoreService.DeleteFlag:input_type -> console.plugin.v1.Key
	5,  // 10: console.plugin.v1.StoreService.CreateComponent:input_type -> console.plugin.v1.Component
	1,  // 11: console.plugin.v1.StoreService.GetComponent:input_type -> console.plugin.v1.Key
	0,  // 12: console.plugin.v1.StoreService.ListComponents:input_type -> console.plugin.v1.Empty
	5,  // 13: console.plugin.v1.StoreService.UpdateComponent:input_type -> console.plugin.v1.Component
	1,  // 14: console.plugin.v1.StoreService.DeleteComponent:input_type -> console.plugin.v1.Key
	7,  // 15: console.plugin.v1.StoreService.RecordCheck:input_type -> console.plugin.v1.Check
	1,  // 16: console.plugin.v1.StoreService.LatestCheck:input_type -> console.plugin.v1.Key
	0,  // 17: console.plugin.v1.StoreService.LatestChecks:input_type -> console.plugin.v1.Empty
	0,  // 18: console.plugin.v1.StoreService.Ping:input_type -> console.plugin.v1.Empty
	0,  // 19: console.plugin.v1.StoreService.CreateFlag:output_type -> console.plugin.v1.Empty
	3,  // 20: console.plugin.v1.StoreService.GetFlag:output_type -> console.plugin.v1.Flag
	4,  // 21: console.plugin.v1.StoreService.ListFlags:output_type -> console.plugin.v1.FlagList
	0,  // 22: console.plugin.v1.StoreService.UpdateFlag:output_type -> console.plugin.v1.Empty
	0,  // 23: console.plugin.v1.StoreService.DeleteFlag:output_type -> console.plugin.v1.Empty
	0,  // 24: console.plugin.v1.StoreService.CreateComponent:output_type -> console.plugin.v1.Empty
	5,  // 25: console.plugin.v1.StoreService.GetComponent:output_type -> console.plugin.v1.Component
	6,  // 26: console.plugin.v1.StoreService.ListComponents:output_type -> console.plugin.v1.ComponentList
	0,  // 27: console.plugin.v1.StoreService.UpdateComponent:output_type -> console.plugin.v1.Empty
	0,  // 28: console.plugin.v1.StoreService.DeleteComponent:output_type -> console.plugin.v1.Empty
	0,  // 29: console.plugin.v1.StoreService.RecordCheck:output_type -> console.plugin.v1.Empty
	7,  // 30: console.plugin.v1.StoreService.LatestCheck:output_type -> console.plugin.v1.Check
	8,  // 31: console.plugin.v1.StoreService.LatestChecks:output_type -> console.plugin.v1.CheckList
	0,  // 32: console.plugin.v1.StoreService.Ping:output_type -> console.plugin.v1.Empty
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_store_proto_init() }
func file_proto_store_proto_init() {
	if File_proto_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_store_proto_rawDesc), len(file_proto_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_store_proto_goTypes,
		DependencyIndexes: file_proto_store_proto_depIdxs,
		MessageInfos:      file_proto_store_proto_msgTypes,
	}.Build()
	File_proto_store_proto = out.File
	file_proto_store_proto_goTypes = nil
	file_proto_store_proto_depIdxs = nil
}
